export const labels = {
  amountToday: "Amount Today:",
  amountTodayVariable: "Cost Today (USD):",
  annualAmount: "Annual Amount:",
  annualPercentChange: "Annual Percent Change:",
  btc: "BTC",
  btcWillingToSpend: "BTC Willing to Spend:",
  currency: "Currency:",
  currencyType: "Currency Type:",
  delay: "Delay (Weeks):",
  effectiveDate: "Effective Date:",
  endDate: "End Date (optional):",
  expense: "Expense:",
  input: {
    active: "Active:",
    close: "\u00D7",
    delete: "Remove",
    name: "Name:",
    placeholder: "Enter item name",
    save: "Save",
    type: "Type:",
  },
  start: "Start (%):",
  types: {
    oneOffFiatVariable: "One-Off Fiat Variable-Date",
    oneOffItem: "One-Off",
    reoccurringItem: "Reoccurring",
  },
  usd: "USD",
};
